In [48]:
import pandas as pd
import os

In [49]:
#IGNORE THIS PART its for retrieving the files from my folders
def filesList():
    os.path.join(os.getcwd(),'air-pollution-datasets')
    mypath = os.path.join(os.getcwd(),'air-pollution-datasets')
    onlyfiles = [os.path.join(mypath, f) for f in os.listdir(mypath) if os.path.isfile(os.path.join(mypath, f))]
    return onlyfiles

In [32]:
filesList()

['C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\CA-2018.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\CA-2019.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\CA-2020.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\IL-2018.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\IL-2019.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\IL-2020.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\MA-2018.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\MA-2019.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\MA-2020.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\NY-2018.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\NY-2019.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\NY-2020.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\WA-2018.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\WA-2019.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\WA-2020.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\WI-2018.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\WI-2019.csv',
 'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\WI-2020.csv']

In [42]:
def createAirPolData():
    list_of_files = filesList()
    air_state_df = pd.DataFrame()
    for file in list_of_files: # loop through each file in the list
        df = pd.read_csv(file) # read csv into data frame
        air_mean = df.groupby('Date')['Daily Mean PM2.5 Concentration'].mean() # group by date and take the mean of pm25
        air_df = pd.DataFrame(air_mean) # convert the results to data frame
        air_df['State'] = file[-11:-9] # add column State and pick the state name from the file name
        air_state_df = pd.concat([air_state_df, air_df]) # concatenate the data frames 
    return air_state_df

In [43]:
st = createAirPolData()

In [50]:
# EXAMPLE 
file = filesList()[0] #change this to ur file in your folder
file

'C:\\Users\\Reem\\Documents\\volunteer-covid-19\\air-pollution-datasets\\CA-2018.csv'

In [51]:
df = pd.read_csv(file) # read csv into data frame

In [52]:
df.head() # check the data frame

,Date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,01/01/2018,AQS,60010007,3,28.1,ug/m3 LC,85,Livermore,1,100.0,88101,PM2.5 - Local Conditions,41860.0,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
1,01/02/2018,AQS,60010007,3,24.5,ug/m3 LC,77,Livermore,1,100.0,88101,PM2.5 - Local Conditions,41860.0,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
2,01/03/2018,AQS,60010007,3,39.0,ug/m3 LC,110,Livermore,1,100.0,88101,PM2.5 - Local Conditions,41860.0,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
3,01/04/2018,AQS,60010007,3,20.9,ug/m3 LC,70,Livermore,1,100.0,88101,PM2.5 - Local Conditions,41860.0,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217
4,01/05/2018,AQS,60010007,3,5.5,ug/m3 LC,23,Livermore,1,100.0,88101,PM2.5 - Local Conditions,41860.0,"San Francisco-Oakland-Hayward, CA",6,California,1,Alameda,37.687526,-121.784217

In [53]:
df.shape # check the number of data in the data frame

(51485, 20)

In [54]:
air_mean = df.groupby('Date')['Daily Mean PM2.5 Concentration'].mean() # group by date and take the mean of pm25
air_mean

Date
01/01/2018    34.696667
01/02/2018    27.249741
01/03/2018    28.133871
01/04/2018    19.480328
01/05/2018    11.334731
01/06/2018    10.451639
01/07/2018    12.844715
01/08/2018     9.346597
01/09/2018     4.134959
01/10/2018     7.538017
01/11/2018    11.084242
01/12/2018    13.341322
01/13/2018    11.511667
01/14/2018    12.146073
01/15/2018    15.554237
01/16/2018    16.544444
01/17/2018    14.851923
01/18/2018    15.269919
01/19/2018     8.505738
01/20/2018     6.750794
01/21/2018    10.098333
01/22/2018     9.128571
01/23/2018     8.373494
01/24/2018    10.028099
01/25/2018     6.594167
01/26/2018     7.880851
01/27/2018     8.997500
01/28/2018     9.132203
01/29/2018    11.050602
01/30/2018    12.941176
                ...
12/02/2018     6.957143
12/03/2018     8.078862
12/04/2018     7.812887
12/05/2018     6.765854
12/06/2018     7.053659
12/07/2018     9.528743
12/08/2018    14.160317
12/09/2018    15.407200
12/10/2018    13.892670
12/11/2018    13.303200
12/12/2018    13.848800
12/13/2018    14.225150
12/14/2018    14.698400
12/15/2018    11.776190
12/16/2018    11.574752
12/17/2018     8.037600
12/18/2018     8.720800
12/19/2018     9.882209
12/20/2018    13.053226
12/21/2018    14.450806
12/22/2018    13.461538
12/23/2018    15.372656
12/24/2018    16.233333
12/25/2018     6.148538
12/26/2018     7.204762
12/27/2018     7.220000
12/28/2018     6.449444
12/29/2018    11.051200
12/30/2018    13.724390
12/31/2018    10.129054
Name: Daily Mean PM2.5 Concentration, Length: 365, dtype: float64

In [55]:
air_df = pd.DataFrame(air_mean) # convert the results to data frame
air_df

            Daily Mean PM2.5 Concentration
Date
01/01/2018                       34.696667
01/02/2018                       27.249741
01/03/2018                       28.133871
01/04/2018                       19.480328
01/05/2018                       11.334731
01/06/2018                       10.451639
01/07/2018                       12.844715
01/08/2018                        9.346597
01/09/2018                        4.134959
01/10/2018                        7.538017
01/11/2018                       11.084242
01/12/2018                       13.341322
01/13/2018                       11.511667
01/14/2018                       12.146073
01/15/2018                       15.554237
01/16/2018                       16.544444
01/17/2018                       14.851923
01/18/2018                       15.269919
01/19/2018                        8.505738
01/20/2018                        6.750794
01/21/2018                       10.098333
01/22/2018                        9.128571
01/23/2018                        8.373494
01/24/2018                       10.028099
01/25/2018                        6.594167
01/26/2018                        7.880851
01/27/2018                        8.997500
01/28/2018                        9.132203
01/29/2018                       11.050602
01/30/2018                       12.941176
...                                    ...
12/02/2018                        6.957143
12/03/2018                        8.078862
12/04/2018                        7.812887
12/05/2018                        6.765854
12/06/2018                        7.053659
12/07/2018                        9.528743
12/08/2018                       14.160317
12/09/2018                       15.407200
12/10/2018                       13.892670
12/11/2018                       13.303200
12/12/2018                       13.848800
12/13/2018                       14.225150
12/14/2018                       14.698400
12/15/2018                       11.776190
12/16/2018                       11.574752
12/17/2018                        8.037600
12/18/2018                        8.720800
12/19/2018                        9.882209
12/20/2018                       13.053226
12/21/2018                       14.450806
12/22/2018                       13.461538
12/23/2018                       15.372656
12/24/2018                       16.233333
12/25/2018                        6.148538
12/26/2018                        7.204762
12/27/2018                        7.220000
12/28/2018                        6.449444
12/29/2018                       11.051200
12/30/2018                       13.724390
12/31/2018                       10.129054

[365 rows x 1 columns]

In [56]:
state_name = file[-11:-9] # getting the state name from the file name you can change these numbers to fit your file
#state_name = 'CA' # or just type it in state_name = 'CA'
state_name

'CA'

In [57]:
air_df['State'] = state_name # add column State and pick the state name from the file name or the other method
air_df

            Daily Mean PM2.5 Concentration State
Date
01/01/2018                       34.696667    CA
01/02/2018                       27.249741    CA
01/03/2018                       28.133871    CA
01/04/2018                       19.480328    CA
01/05/2018                       11.334731    CA
01/06/2018                       10.451639    CA
01/07/2018                       12.844715    CA
01/08/2018                        9.346597    CA
01/09/2018                        4.134959    CA
01/10/2018                        7.538017    CA
01/11/2018                       11.084242    CA
01/12/2018                       13.341322    CA
01/13/2018                       11.511667    CA
01/14/2018                       12.146073    CA
01/15/2018                       15.554237    CA
01/16/2018                       16.544444    CA
01/17/2018                       14.851923    CA
01/18/2018                       15.269919    CA
01/19/2018                        8.505738    CA
01/20/2018                        6.750794    CA
01/21/2018                       10.098333    CA
01/22/2018                        9.128571    CA
01/23/2018                        8.373494    CA
01/24/2018                       10.028099    CA
01/25/2018                        6.594167    CA
01/26/2018                        7.880851    CA
01/27/2018                        8.997500    CA
01/28/2018                        9.132203    CA
01/29/2018                       11.050602    CA
01/30/2018                       12.941176    CA
...                                    ...   ...
12/02/2018                        6.957143    CA
12/03/2018                        8.078862    CA
12/04/2018                        7.812887    CA
12/05/2018                        6.765854    CA
12/06/2018                        7.053659    CA
12/07/2018                        9.528743    CA
12/08/2018                       14.160317    CA
12/09/2018                       15.407200    CA
12/10/2018                       13.892670    CA
12/11/2018                       13.303200    CA
12/12/2018                       13.848800    CA
12/13/2018                       14.225150    CA
12/14/2018                       14.698400    CA
12/15/2018                       11.776190    CA
12/16/2018                       11.574752    CA
12/17/2018                        8.037600    CA
12/18/2018                        8.720800    CA
12/19/2018                        9.882209    CA
12/20/2018                       13.053226    CA
12/21/2018                       14.450806    CA
12/22/2018                       13.461538    CA
12/23/2018                       15.372656    CA
12/24/2018                       16.233333    CA
12/25/2018                        6.148538    CA
12/26/2018                        7.204762    CA
12/27/2018                        7.220000    CA
12/28/2018                        6.449444    CA
12/29/2018                       11.051200    CA
12/30/2018                       13.724390    CA
12/31/2018                       10.129054    CA

[365 rows x 2 columns]

In [58]:
# last step concatenate data frames as shown in the function